### ISSUE TITLE
seer in bioconda

### ISSUE THREAD

**Issue by aschuerch** [johnlees/seer#48]
I am having troubles installing seer on our HPC (no root rights). We devised a workaround for now but I would be very grateful if you could consider adding seer as a package to the bioconda package manager http://bioconda.github.io/

**Comment by johnlees** [comment]
Installation still seems to be tricky! I'm happy to do this when I next get a chance

**Comment by karel-brinda** [comment]
Hi @johnlees and @aschuerch, I would be happy to help you with adding SEER to Bioconda. I also think that SEER should be available from there. My current problem is that I am not able to compile SEER even on my own computer – the current version of Makefile seems to be very specific for John's computer (`export PREFIX=${HOME}/software`, etc.). I think that it would be very reasonable to use CMake for compilation because many different external libraries are required and adding their paths is not trivial. In particular, with packaging systems such as Bioconda, it is not possible to rely on some fixed pre-selected paths as most of the libraries will be installed in "non-standard" locations. John, do you think that you could write `CMakeLists.txt` for SEER?

**Comment by johnlees** [comment]
Thanks for the advice @karel-brinda, and the offer of help. I agree that the install is still not great – I've been planning to improve this for a while.

I'll go ahead and try and get it to work with CMake, though I'm afraid I won't get around to this for another month or so.

Perhaps the binaries might do the job for now?

**Comment by johnlees** [comment]
We've had a go at this (with the help of @Slugger70), but need a newer compiler for it to work:
https://github.com/bioconda/bioconda-recipes/pull/5005
 
This is being added to bioconda at the moment, so I'm hopeful that we can have seer in bioconda (and docker) within a couple of weeks

**Comment by apredeus** [comment]
Hello everybody, any news on this?

**Comment by johnlees** [comment]
We tried this a while ago but got stuck because the bioconda gcc version
was <4.9. Looks like v5 and above are available in conda-forge now so I'm
happy to take a look again when I get a chance.
In the meantime you could also look at https://anaconda.org/bioconda/pyseer

**Comment by apredeus** [comment]
I am installing pySEER right now, yes! Would you say they are equivalent to use right now? I'm very new to all this. Thanks!

**Comment by johnlees** [comment]
pyseer is the version we support now – it has more features, is of similar
speed to seer and should produce identical results. So yes, I would
definitely go with pyseer!
Here are the docs: https://pyseer.readthedocs.io/en/master/

**Comment by johnlees** [comment]
Currently sorting this out, in case it is still useful to anyone
