### ISSUE TITLE
Segmentation fault when running seer

### ISSUE THREAD

**Issue by nysdan** [johnlees/seer#60]
Hello, first of all, thank you for this package. 
I'm trying to run seer on a group of genome assemblies. So far, k-mer counting using fsm lite and mash have worked fine, although, the R script part did't run as in the Usage page, but I ran the commands "by hand" directly or R and got the distances table and the all_structure file.
Now, moving to next step, I tried to run 
seer -k fsm_out00.gz --pheno metadata.pheno --struct all_structure --threads 4 --print_samples > significant_kmers.txt 
with the first fsm_out gz file

This is the shell output:
seer: sequence element enrichment analysis
Detected binary phenotype
Segmentation fault (`core' generado)

and the significant_kmers.txt file is created but blank.

I used the v1.1.3 static release on a Fedora 24 system.

I'll appreciate if you can give me some suggestions about what might be the problem and how to fix it.

Thank you in advance.

**Comment by johnlees** [comment]
Hi,
Sorry for the delayed reply. The first thing I'd recommend is trying the 'static_all" release: https://github.com/johnlees/seer/releases/download/v1.1.3/seer_v1.1.3_static_all.tar.gz
as this is likely due to the operating system having different packages available (I compiled on Ubuntu).

If that doesn't work, you could try the linuxbrew release (https://github.com/johnlees/seer/issues/59), the virtual machine (ftp://ftp.sanger.ac.uk/pub/pathogens/pathogens-vm/pathogens-vm.latest.ova) or compiling from source. Let me know if you need any help with these.

**Comment by nysdan** [comment]
Thank you for your reply, but unfortunatly it didn't work. I'll just use the VirtualBox.
